import type { GetStaticPropsContext, NextPage } from 'next';
import Head from 'next/head';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';

const Home: NextPage = () => (
  <div>
    <Head>
      <title>Create Next App</title>
      <meta name='description' content='Generated by create next app' />
      <link rel='icon' href='/favicon.ico' />
    </Head>

    <main id='skip' className='py-8'>
      <div className='badge'>neutral</div>
      <div className='badge badge-primary'>primary</div>
      <div className='badge badge-secondary'>secondary</div>
      <div className='badge badge-accent'>accent</div>
      <div className='badge badge-ghost'>ghost</div>

      <div className='card'>
        <pre>{JSON.stringify({}, null, 2)}</pre>
      </div>
    </main>
  </div>
);

export default Home;

export async function getStaticProps({ locale }: GetStaticPropsContext) {
  return {
    props: {
      ...(await serverSideTranslations(locale, ['common']))
      // Will be passed to the page component as props
    }
  };
}
